
// Objective-C API for talking to the following Go packages
//
//	github.com/renatoathaydes/go-hash/mobileapi
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobileapi_FRAMEWORK_H__
#define __Mobileapi_FRAMEWORK_H__

#include "Mobileapi.objc.h"
#include "universe.objc.h"

#endif
