// Objective-C API for talking to github.com/renatoathaydes/go-hash/mobileapi Go package.
//   gobind -lang=objc github.com/renatoathaydes/go-hash/mobileapi
//
// File is generated by gobind. Do not edit.

#ifndef __Mobileapi_H__
#define __Mobileapi_H__

@import Foundation;
#include "Universe.objc.h"


@class MobileapiDatabase;
@class MobileapiEntry;
@class MobileapiEntryIterator;
@class MobileapiGroupIterator;

@interface MobileapiDatabase : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)fileName;
- (void)setFileName:(NSString*)v;
- (MobileapiGroupIterator*)iter;
@end

@interface MobileapiEntry : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)description;
- (NSString*)name;
- (NSString*)password;
- (int64_t)updatedAt;
- (NSString*)url;
- (NSString*)username;
@end

@interface MobileapiEntryIterator : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)group;
- (void)setGroup:(NSString*)v;
- (MobileapiEntry*)next;
@end

@interface MobileapiGroupIterator : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (MobileapiEntryIterator*)next;
@end

FOUNDATION_EXPORT MobileapiDatabase* MobileapiReadDatabase(NSString* filePath, NSString* password, NSError** error);

#endif
